### PR TITLE
Fix: LU decomposition, determinant

### PR DESCRIPTION
**Pull request by miniBill**
Honestly I'm tempted to squash the whole history, it's kinda silly

### CODE REVIEW

**Comment by miniBill** [comment]
Next step is to remove `luNoPivotSingle` and fix the "solving systems" code.
And probably do an efficiency pass.

This took waaaay too much time, but it's apparently impossible to find a simple _and_ correct implementation of LU decomposition with pivoting.

**Comment by ryry0** [comment]
WOW, thank you so much for your effort and solving this issue :)) I'm amazed! Will you open a new PR for these 
> Next step is to remove luNoPivotSingle and fix the "solving systems" code.

or will you add them to this one?

**Comment by miniBill** [comment]
Yeah, it's going to be a separate PR.
How do you feel about renaming `luDecomp` to `luDecompose` by the way? The type signature is already different so it's going to be a breaking change anyway :shrug:

**Comment by ryry0** [comment]
That's fine, go right ahead!

**Comment by miniBill** [comment]
Ok, pushed

**Pull request merged**
