### PR TITLE
Use an API based on explicit errors

### PR DESCRIPTION
**Pull request by miniBill**
This is a big change, and it would be completely reasonable of you to reject it if it's not the direction you want to go in.

Basically, this PR moves the error handling from being internal to being external.

### CODE REVIEW

**Comment by ryry0** [comment]
Hi!! Thank you for contributing :) I'm open to the idea of merging, I realize my error handling wasn't that great and a little kludgy. In retrospect, it looks like past me when I was writing it was trying to go for some custom monadicish error logging but past me didn't quite understand how to do that fully, and I'm not sure if elm can really support that syntax/pattern super well outside of the builtin Maybe, etc.

Would you be able to explain a bit of what you did, how this PR solved the pain point you were having with the library, and provide an example of what the new usage syntax looks like? :)

**Comment by miniBill** [comment]
What I did was simplify the `Matrix` type to only have the "Ok" variant.

The new syntax is just regular usage of `Result` in Elm. Something like:

```elm
similarity left right =
    let
        raw =
            Matrix.dot
                (Matrix.transpose left.choices)
                (Matrix.transpose right.choices)
                |> Result.withDefault -1

        ( rows, cols ) =
            Matrix.size left.choices
    in
    raw / toFloat (rows * cols)
```

In this case I'm using `Result.withDefault` because I know the vectors will have the correct size, but I could deal with the error and know what went wrong.
    
Main pain point of the old API is that you could do several calculations, ask for the list of floats and get an empty list without knowing what went wrong.

**Comment by ryry0** [comment]
Thank you for also working on #2 :) I really appreciate you putting in the time to do so!

I'm traveling and moving out of my apartment this week but I'll try to make some time to look at this in depth as soon as I can!

**Comment by miniBill** [comment]
*poke*

**Comment by ryry0** [comment]
Hi! Apologies for the extremely late reply. Life got in the way.

I've played with it a bit, and I'm very positive towards the changes - I even took a look at #4 and am excited that it can invert previously non-invertible matrices.  Just a couple things:

1. I just wanted to ask if you think there's a way to streamline creation of matrices then usage of them in a function without needing an unwrapper - this was my reasoning behind my original design: to be able to write `a = <matrix>` and `b = <matrix>`, and immediately use them in a function `mul a b` - like the example given in the doc.  Is there a a halfway-house of some sort? I noticed you using `force` in the test for #4, for example. If not, I'm happy to merge as long as the doc is updated.
2. In #4 you implemented pivoting in `inverse`, but not in `luNoPivotSingle` - would it be possible to implement pivoting here so that `solveV`, `luDecomp`, and `det` have correct behavior as well?

Thanks again for your contribution :))

**Comment by miniBill** [comment]
1. I don't think so? One thing that could help is adding helpers for building matrices up to size - say - 4 without needing to unwrap. I'll open a separate PR for it so we can discuss the API and tradeoffs
2. Discussion moved to #4

**Comment by miniBill** [comment]
https://github.com/miniBill/elm-numeric/pull/1 Does this API look reasonable?

**Comment by ryry0** [comment]
Yeah! That looks great. Thanks for coming up with that idea. I think that'll cover most cases where users would type out by hand anyway :).

**Comment by miniBill** [comment]
Ok, I've merged it into this PR

**Comment by miniBill** [comment]
I think it might make sense to also add 1x4, 4x1 and 4x4, but those can be added in a `.1` if needed

**Comment by ryry0** [comment]
Merged :) Thanks again. I'll update the library when you're done with the LU stuff?

**Comment by miniBill** [comment]
Makes sense

**Pull request merged**
